import type { Role } from "@/lib/session";

// Espelho do catálogo público retornado pelo backend. O Administrador do tenant
// nunca depende do conteúdo persistido da sessão para manter o acesso total.
export const TENANT_ADMIN_PERMISSIONS = [
  "dashboard.read",
  "dashboard.manage",
  "dashboard.delete",
  "users.read",
  "users.manage",
  "users.delete",
  "departments.read",
  "departments.manage",
  "departments.delete",
  "roles.read",
  "roles.manage",
  "roles.delete",
  "crm.read",
  "crm.manage",
  "contacts.read",
  "contacts.manage",
  "contacts.delete",
  "conversations.read",
  "conversations.assign",
  "conversations.manage",
  "messages.send",
  "connections.read",
  "connections.manage",
  "connections.delete",
  "groups.read",
  "groups.manage",
  "history.read",
  "chat.contacts.edit",
  "chat.contacts.create",
  "chat.customer_link.edit",
  "chat.tags.use",
  "chat.tags.manage",
  "chat.tags.read",
  "chat.tags.delete",
  "chat.leads.read",
  "leads.manage",
  "notifications.read",
  "notifications.manage",
  "automations.read",
  "automations.manage",
  "automations.delete",
  "chat.contacts.read",
  "chat.phone.read",
  "chat.messages.delete",
  "chat.messages.edit",
  "chat.quick_replies.read",
  "chat.quick_replies.manage",
  "chat.quick_replies.delete",
  "tickets.read",
  "tickets.create",
  "tickets.update",
  "tickets.assign",
  "tickets.status.update",
  "tickets.comment",
  "tickets.attachments.upload",
  "tickets.attachments.delete",
  "tickets.manage",
  "campaigns.read",
  "campaigns.create",
  "campaigns.update",
  "campaigns.schedule",
  "campaigns.start",
  "campaigns.pause",
  "campaigns.cancel",
  "campaigns.duplicate",
  "campaigns.recipients.read",
  "campaigns.manage",
  "campaigns.delete",
  "schedules.read",
  "schedules.manage",
  "schedules.delete",
  "bot_flows.read",
  "bot_flows.manage",
  "bot_flows.delete",
  "ai_agents.read",
  "ai_agents.manage",
  "ai_agents.delete",
  "settings.read",
  "settings.manage",
  "settings.delete",
  "tickets.delete",
  "chat.contacts.block",
  "chat.audio.send",
  "chat.agent_name.show",
  "chat.conversations.view_all_active",
] as const;

export function effectiveSessionPermissions(
  role: Role,
  permissions: readonly string[] | undefined,
): string[] {
  return role === "admin" ? [...TENANT_ADMIN_PERMISSIONS] : [...(permissions ?? [])];
}
