import type { Role } from "@/lib/session";

// Espelho do catálogo público retornado pelo backend. O Administrador do tenant
// nunca depende do conteúdo persistido da sessão para manter o acesso total.
export const TENANT_ADMIN_PERMISSIONS = [
  "dashboard.read",
  "dashboard.create",
  "dashboard.update",
  "dashboard.delete",
  "users.read",
  "users.create",
  "users.update",
  "users.delete",
  "departments.read",
  "departments.create",
  "departments.update",
  "departments.delete",
  "roles.read",
  "roles.create",
  "roles.update",
  "roles.delete",
  "contacts.read",
  "contacts.create",
  "contacts.update",
  "contacts.delete",
  "contacts.additional_fields.read",
  "conversations.read",
  "conversations.assign",
  "messages.send",
  "connections.read",
  "connections.create",
  "connections.update",
  "connections.delete",
  "groups.read",
  "groups.create",
  "groups.update",
  "groups.leave",
  "history.read",
  "chat.tags.read",
  "chat.tags.create",
  "chat.tags.update",
  "chat.tags.delete",
  "automations.read",
  "automations.create",
  "automations.update",
  "automations.delete",
  "chat.phone.read",
  "chat.messages.delete",
  "chat.messages.edit",
  "chat.quick_replies.read",
  "chat.quick_replies.create",
  "chat.quick_replies.update",
  "chat.quick_replies.delete",
  "tickets.read",
  "tickets.create",
  "tickets.update",
  "tickets.delete",
  "campaigns.read",
  "campaigns.create",
  "campaigns.update",
  "campaigns.delete",
  "schedules.read",
  "schedules.create",
  "schedules.update",
  "schedules.delete",
  "bot_flows.read",
  "bot_flows.create",
  "bot_flows.update",
  "bot_flows.delete",
  "ai_agents.read",
  "ai_agents.create",
  "ai_agents.update",
  "ai_agents.delete",
  "settings.manage",
  "chat.agent_name.show",
  "chat.conversations.view_all_active",
  "chat.bulk_actions.execute",
] as const;

export function effectiveSessionPermissions(
  role: Role,
  permissions: readonly string[] | undefined,
): string[] {
  return role === "admin" ? [...TENANT_ADMIN_PERMISSIONS] : [...(permissions ?? [])];
}
