type ScheduleType = "message" | "task";
type ScheduleStatus = "pending" | "completed";
export type ScheduleAttachment = {
  fileName: string;
  mimeType: string;
  size: number;
  dataUrl: string;
};
export type ApiSchedule = {
  id: string;
  identifier: string;
  type: ScheduleType;
  title: string;
  destination: string;
  conversationId?: string;
  scheduledAt: string;
  recurrence: "once" | "weekly" | "monthly";
  delivery: boolean;
  status: ScheduleStatus;
  connectionId: string;
  departmentId: string;
  content: string;
  recipientIds: string[];
  recipients: Array<{ id: string; name: string }>;
  recurrenceDays: string[];
  recurrenceLimit: string;
  recurrenceUntil: string;
  assignedMembershipId: string;
  attachmentName: string | null;
  attachment?: ScheduleAttachment | null;
  dueAt?: string | null;
  executionStatus?: "PENDING" | "CLAIMED" | "QUEUED" | "SENT" | "FAILED" | null;
  claimedAt?: string | null;
  messageId?: string | null;
  attempts?: number;
  lastError?: string | null;
  completedAt?: string | null;
};
