ALTER TABLE "departments" ALTER COLUMN "color" SET DEFAULT '#3B82F6';
ALTER TABLE "customers" ALTER COLUMN "color" SET DEFAULT '#3B82F6';
ALTER TABLE "contact_departments" ALTER COLUMN "color" SET DEFAULT '#3B82F6';
ALTER TABLE "contact_profiles" ALTER COLUMN "color" SET DEFAULT '#3B82F6';
ALTER TABLE "tags" ALTER COLUMN "color" SET DEFAULT '#3B82F6';
