/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PerfisRouteImport } from './routes/perfis'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MensagensRapidasRouteImport } from './routes/mensagens-rapidas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstanciasRouteImport } from './routes/instancias'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FilasRouteImport } from './routes/filas'
import { Route as EtiquetasRouteImport } from './routes/etiquetas'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DepartamentosRouteImport } from './routes/departamentos'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as AtendentesRouteImport } from './routes/atendentes'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AgenteIaRouteImport } from './routes/agente-ia'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as AtendimentoIndexRouteImport } from './routes/atendimento.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as InboxConversationIdRouteImport } from './routes/inbox.$conversationId'
import { Route as ConfiguracoesUsuariosRouteImport } from './routes/configuracoes.usuarios'
import { Route as ConfiguracoesSegurancaRouteImport } from './routes/configuracoes.seguranca'
import { Route as ConfiguracoesPermissoesRouteImport } from './routes/configuracoes.permissoes'
import { Route as ConfiguracoesMensagensRouteImport } from './routes/configuracoes.mensagens'
import { Route as ConfiguracoesIntegracoesRouteImport } from './routes/configuracoes.integracoes'
import { Route as ConfiguracoesHorariosRouteImport } from './routes/configuracoes.horarios'
import { Route as ConfiguracoesGeralRouteImport } from './routes/configuracoes.geral'
import { Route as ConfiguracoesEmpresaRouteImport } from './routes/configuracoes.empresa'
import { Route as AtendimentoPerfilRouteImport } from './routes/atendimento.perfil'
import { Route as AtendimentoInboxRouteImport } from './routes/atendimento.inbox'
import { Route as AtendimentoHistoricoRouteImport } from './routes/atendimento.historico'
import { Route as AtendimentoFavoritosRouteImport } from './routes/atendimento.favoritos'
import { Route as AtendimentoClientesRouteImport } from './routes/atendimento.clientes'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminMonitoramentoRouteImport } from './routes/admin.monitoramento'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLicencasRouteImport } from './routes/admin.licencas'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminAssinaturasRouteImport } from './routes/admin.assinaturas'
import { Route as AdminEmpresasTenantIdRouteImport } from './routes/admin.empresas.$tenantId'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisRoute = PerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRapidasRoute = MensagensRapidasRouteImport.update({
  id: '/mensagens-rapidas',
  path: '/mensagens-rapidas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstanciasRoute = InstanciasRouteImport.update({
  id: '/instancias',
  path: '/instancias',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FilasRoute = FilasRouteImport.update({
  id: '/filas',
  path: '/filas',
  getParentRoute: () => rootRouteImport,
} as any)
const EtiquetasRoute = EtiquetasRouteImport.update({
  id: '/etiquetas',
  path: '/etiquetas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartamentosRoute = DepartamentosRouteImport.update({
  id: '/departamentos',
  path: '/departamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendentesRoute = AtendentesRouteImport.update({
  id: '/atendentes',
  path: '/atendentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteIaRoute = AgenteIaRouteImport.update({
  id: '/agente-ia',
  path: '/agente-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InboxRoute,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const AtendimentoIndexRoute = AtendimentoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const InboxConversationIdRoute = InboxConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => InboxRoute,
} as any)
const ConfiguracoesUsuariosRoute = ConfiguracoesUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesSegurancaRoute = ConfiguracoesSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesPermissoesRoute = ConfiguracoesPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesMensagensRoute = ConfiguracoesMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesIntegracoesRoute =
  ConfiguracoesIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesHorariosRoute = ConfiguracoesHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesGeralRoute = ConfiguracoesGeralRouteImport.update({
  id: '/geral',
  path: '/geral',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesEmpresaRoute = ConfiguracoesEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const AtendimentoPerfilRoute = AtendimentoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoInboxRoute = AtendimentoInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoHistoricoRoute = AtendimentoHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoFavoritosRoute = AtendimentoFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoClientesRoute = AtendimentoClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoramentoRoute = AdminMonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicencasRoute = AdminLicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasTenantIdRoute = AdminEmpresasTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => AdminEmpresasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agente-ia': typeof AgenteIaRoute
  '/ajuda': typeof AjudaRoute
  '/atendentes': typeof AtendentesRoute
  '/atendimento': typeof AtendimentoRouteWithChildren
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/chamados': typeof ChamadosRoute
  '/chatbot': typeof ChatbotRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contatos': typeof ContatosRoute
  '/departamentos': typeof DepartamentosRoute
  '/empresas': typeof EmpresasRoute
  '/etiquetas': typeof EtiquetasRoute
  '/filas': typeof FilasRoute
  '/historico': typeof HistoricoRoute
  '/inbox': typeof InboxRouteWithChildren
  '/instancias': typeof InstanciasRoute
  '/login': typeof LoginRoute
  '/mensagens-rapidas': typeof MensagensRapidasRoute
  '/perfil': typeof PerfilRoute
  '/perfis': typeof PerfisRoute
  '/relatorios': typeof RelatoriosRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/licencas': typeof AdminLicencasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/monitoramento': typeof AdminMonitoramentoRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/atendimento/clientes': typeof AtendimentoClientesRoute
  '/atendimento/favoritos': typeof AtendimentoFavoritosRoute
  '/atendimento/historico': typeof AtendimentoHistoricoRoute
  '/atendimento/inbox': typeof AtendimentoInboxRoute
  '/atendimento/perfil': typeof AtendimentoPerfilRoute
  '/configuracoes/empresa': typeof ConfiguracoesEmpresaRoute
  '/configuracoes/geral': typeof ConfiguracoesGeralRoute
  '/configuracoes/horarios': typeof ConfiguracoesHorariosRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/mensagens': typeof ConfiguracoesMensagensRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/configuracoes/seguranca': typeof ConfiguracoesSegurancaRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/atendimento/': typeof AtendimentoIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/admin/empresas/$tenantId': typeof AdminEmpresasTenantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agente-ia': typeof AgenteIaRoute
  '/ajuda': typeof AjudaRoute
  '/atendentes': typeof AtendentesRoute
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/chamados': typeof ChamadosRoute
  '/chatbot': typeof ChatbotRoute
  '/clientes': typeof ClientesRoute
  '/contatos': typeof ContatosRoute
  '/departamentos': typeof DepartamentosRoute
  '/empresas': typeof EmpresasRoute
  '/etiquetas': typeof EtiquetasRoute
  '/filas': typeof FilasRoute
  '/historico': typeof HistoricoRoute
  '/instancias': typeof InstanciasRoute
  '/login': typeof LoginRoute
  '/mensagens-rapidas': typeof MensagensRapidasRoute
  '/perfil': typeof PerfilRoute
  '/perfis': typeof PerfisRoute
  '/relatorios': typeof RelatoriosRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/licencas': typeof AdminLicencasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/monitoramento': typeof AdminMonitoramentoRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/atendimento/clientes': typeof AtendimentoClientesRoute
  '/atendimento/favoritos': typeof AtendimentoFavoritosRoute
  '/atendimento/historico': typeof AtendimentoHistoricoRoute
  '/atendimento/inbox': typeof AtendimentoInboxRoute
  '/atendimento/perfil': typeof AtendimentoPerfilRoute
  '/configuracoes/empresa': typeof ConfiguracoesEmpresaRoute
  '/configuracoes/geral': typeof ConfiguracoesGeralRoute
  '/configuracoes/horarios': typeof ConfiguracoesHorariosRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/mensagens': typeof ConfiguracoesMensagensRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/configuracoes/seguranca': typeof ConfiguracoesSegurancaRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/admin': typeof AdminIndexRoute
  '/atendimento': typeof AtendimentoIndexRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/admin/empresas/$tenantId': typeof AdminEmpresasTenantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agente-ia': typeof AgenteIaRoute
  '/ajuda': typeof AjudaRoute
  '/atendentes': typeof AtendentesRoute
  '/atendimento': typeof AtendimentoRouteWithChildren
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/chamados': typeof ChamadosRoute
  '/chatbot': typeof ChatbotRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contatos': typeof ContatosRoute
  '/departamentos': typeof DepartamentosRoute
  '/empresas': typeof EmpresasRoute
  '/etiquetas': typeof EtiquetasRoute
  '/filas': typeof FilasRoute
  '/historico': typeof HistoricoRoute
  '/inbox': typeof InboxRouteWithChildren
  '/instancias': typeof InstanciasRoute
  '/login': typeof LoginRoute
  '/mensagens-rapidas': typeof MensagensRapidasRoute
  '/perfil': typeof PerfilRoute
  '/perfis': typeof PerfisRoute
  '/relatorios': typeof RelatoriosRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/licencas': typeof AdminLicencasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/monitoramento': typeof AdminMonitoramentoRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/atendimento/clientes': typeof AtendimentoClientesRoute
  '/atendimento/favoritos': typeof AtendimentoFavoritosRoute
  '/atendimento/historico': typeof AtendimentoHistoricoRoute
  '/atendimento/inbox': typeof AtendimentoInboxRoute
  '/atendimento/perfil': typeof AtendimentoPerfilRoute
  '/configuracoes/empresa': typeof ConfiguracoesEmpresaRoute
  '/configuracoes/geral': typeof ConfiguracoesGeralRoute
  '/configuracoes/horarios': typeof ConfiguracoesHorariosRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/mensagens': typeof ConfiguracoesMensagensRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/configuracoes/seguranca': typeof ConfiguracoesSegurancaRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/atendimento/': typeof AtendimentoIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/admin/empresas/$tenantId': typeof AdminEmpresasTenantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agente-ia'
    | '/ajuda'
    | '/atendentes'
    | '/atendimento'
    | '/automacoes'
    | '/campanhas'
    | '/chamados'
    | '/chatbot'
    | '/clientes'
    | '/configuracoes'
    | '/contatos'
    | '/departamentos'
    | '/empresas'
    | '/etiquetas'
    | '/filas'
    | '/historico'
    | '/inbox'
    | '/instancias'
    | '/login'
    | '/mensagens-rapidas'
    | '/perfil'
    | '/perfis'
    | '/relatorios'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/financeiro'
    | '/admin/licencas'
    | '/admin/logs'
    | '/admin/monitoramento'
    | '/admin/planos'
    | '/admin/suporte'
    | '/atendimento/clientes'
    | '/atendimento/favoritos'
    | '/atendimento/historico'
    | '/atendimento/inbox'
    | '/atendimento/perfil'
    | '/configuracoes/empresa'
    | '/configuracoes/geral'
    | '/configuracoes/horarios'
    | '/configuracoes/integracoes'
    | '/configuracoes/mensagens'
    | '/configuracoes/permissoes'
    | '/configuracoes/seguranca'
    | '/configuracoes/usuarios'
    | '/inbox/$conversationId'
    | '/admin/'
    | '/atendimento/'
    | '/configuracoes/'
    | '/inbox/'
    | '/admin/empresas/$tenantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agente-ia'
    | '/ajuda'
    | '/atendentes'
    | '/automacoes'
    | '/campanhas'
    | '/chamados'
    | '/chatbot'
    | '/clientes'
    | '/contatos'
    | '/departamentos'
    | '/empresas'
    | '/etiquetas'
    | '/filas'
    | '/historico'
    | '/instancias'
    | '/login'
    | '/mensagens-rapidas'
    | '/perfil'
    | '/perfis'
    | '/relatorios'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/financeiro'
    | '/admin/licencas'
    | '/admin/logs'
    | '/admin/monitoramento'
    | '/admin/planos'
    | '/admin/suporte'
    | '/atendimento/clientes'
    | '/atendimento/favoritos'
    | '/atendimento/historico'
    | '/atendimento/inbox'
    | '/atendimento/perfil'
    | '/configuracoes/empresa'
    | '/configuracoes/geral'
    | '/configuracoes/horarios'
    | '/configuracoes/integracoes'
    | '/configuracoes/mensagens'
    | '/configuracoes/permissoes'
    | '/configuracoes/seguranca'
    | '/configuracoes/usuarios'
    | '/inbox/$conversationId'
    | '/admin'
    | '/atendimento'
    | '/configuracoes'
    | '/inbox'
    | '/admin/empresas/$tenantId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agente-ia'
    | '/ajuda'
    | '/atendentes'
    | '/atendimento'
    | '/automacoes'
    | '/campanhas'
    | '/chamados'
    | '/chatbot'
    | '/clientes'
    | '/configuracoes'
    | '/contatos'
    | '/departamentos'
    | '/empresas'
    | '/etiquetas'
    | '/filas'
    | '/historico'
    | '/inbox'
    | '/instancias'
    | '/login'
    | '/mensagens-rapidas'
    | '/perfil'
    | '/perfis'
    | '/relatorios'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/financeiro'
    | '/admin/licencas'
    | '/admin/logs'
    | '/admin/monitoramento'
    | '/admin/planos'
    | '/admin/suporte'
    | '/atendimento/clientes'
    | '/atendimento/favoritos'
    | '/atendimento/historico'
    | '/atendimento/inbox'
    | '/atendimento/perfil'
    | '/configuracoes/empresa'
    | '/configuracoes/geral'
    | '/configuracoes/horarios'
    | '/configuracoes/integracoes'
    | '/configuracoes/mensagens'
    | '/configuracoes/permissoes'
    | '/configuracoes/seguranca'
    | '/configuracoes/usuarios'
    | '/inbox/$conversationId'
    | '/admin/'
    | '/atendimento/'
    | '/configuracoes/'
    | '/inbox/'
    | '/admin/empresas/$tenantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgenteIaRoute: typeof AgenteIaRoute
  AjudaRoute: typeof AjudaRoute
  AtendentesRoute: typeof AtendentesRoute
  AtendimentoRoute: typeof AtendimentoRouteWithChildren
  AutomacoesRoute: typeof AutomacoesRoute
  CampanhasRoute: typeof CampanhasRoute
  ChamadosRoute: typeof ChamadosRoute
  ChatbotRoute: typeof ChatbotRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  ContatosRoute: typeof ContatosRoute
  DepartamentosRoute: typeof DepartamentosRoute
  EmpresasRoute: typeof EmpresasRoute
  EtiquetasRoute: typeof EtiquetasRoute
  FilasRoute: typeof FilasRoute
  HistoricoRoute: typeof HistoricoRoute
  InboxRoute: typeof InboxRouteWithChildren
  InstanciasRoute: typeof InstanciasRoute
  LoginRoute: typeof LoginRoute
  MensagensRapidasRoute: typeof MensagensRapidasRoute
  PerfilRoute: typeof PerfilRoute
  PerfisRoute: typeof PerfisRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis': {
      id: '/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof PerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens-rapidas': {
      id: '/mensagens-rapidas'
      path: '/mensagens-rapidas'
      fullPath: '/mensagens-rapidas'
      preLoaderRoute: typeof MensagensRapidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instancias': {
      id: '/instancias'
      path: '/instancias'
      fullPath: '/instancias'
      preLoaderRoute: typeof InstanciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filas': {
      id: '/filas'
      path: '/filas'
      fullPath: '/filas'
      preLoaderRoute: typeof FilasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etiquetas': {
      id: '/etiquetas'
      path: '/etiquetas'
      fullPath: '/etiquetas'
      preLoaderRoute: typeof EtiquetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departamentos': {
      id: '/departamentos'
      path: '/departamentos'
      fullPath: '/departamentos'
      preLoaderRoute: typeof DepartamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendentes': {
      id: '/atendentes'
      path: '/atendentes'
      fullPath: '/atendentes'
      preLoaderRoute: typeof AtendentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente-ia': {
      id: '/agente-ia'
      path: '/agente-ia'
      fullPath: '/agente-ia'
      preLoaderRoute: typeof AgenteIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof InboxRoute
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/atendimento/': {
      id: '/atendimento/'
      path: '/'
      fullPath: '/atendimento/'
      preLoaderRoute: typeof AtendimentoIndexRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/inbox/$conversationId': {
      id: '/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof InboxConversationIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/configuracoes/usuarios': {
      id: '/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof ConfiguracoesUsuariosRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/seguranca': {
      id: '/configuracoes/seguranca'
      path: '/seguranca'
      fullPath: '/configuracoes/seguranca'
      preLoaderRoute: typeof ConfiguracoesSegurancaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/permissoes': {
      id: '/configuracoes/permissoes'
      path: '/permissoes'
      fullPath: '/configuracoes/permissoes'
      preLoaderRoute: typeof ConfiguracoesPermissoesRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/mensagens': {
      id: '/configuracoes/mensagens'
      path: '/mensagens'
      fullPath: '/configuracoes/mensagens'
      preLoaderRoute: typeof ConfiguracoesMensagensRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/integracoes': {
      id: '/configuracoes/integracoes'
      path: '/integracoes'
      fullPath: '/configuracoes/integracoes'
      preLoaderRoute: typeof ConfiguracoesIntegracoesRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/horarios': {
      id: '/configuracoes/horarios'
      path: '/horarios'
      fullPath: '/configuracoes/horarios'
      preLoaderRoute: typeof ConfiguracoesHorariosRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/geral': {
      id: '/configuracoes/geral'
      path: '/geral'
      fullPath: '/configuracoes/geral'
      preLoaderRoute: typeof ConfiguracoesGeralRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/empresa': {
      id: '/configuracoes/empresa'
      path: '/empresa'
      fullPath: '/configuracoes/empresa'
      preLoaderRoute: typeof ConfiguracoesEmpresaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/atendimento/perfil': {
      id: '/atendimento/perfil'
      path: '/perfil'
      fullPath: '/atendimento/perfil'
      preLoaderRoute: typeof AtendimentoPerfilRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/inbox': {
      id: '/atendimento/inbox'
      path: '/inbox'
      fullPath: '/atendimento/inbox'
      preLoaderRoute: typeof AtendimentoInboxRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/historico': {
      id: '/atendimento/historico'
      path: '/historico'
      fullPath: '/atendimento/historico'
      preLoaderRoute: typeof AtendimentoHistoricoRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/favoritos': {
      id: '/atendimento/favoritos'
      path: '/favoritos'
      fullPath: '/atendimento/favoritos'
      preLoaderRoute: typeof AtendimentoFavoritosRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/clientes': {
      id: '/atendimento/clientes'
      path: '/clientes'
      fullPath: '/atendimento/clientes'
      preLoaderRoute: typeof AtendimentoClientesRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoramento': {
      id: '/admin/monitoramento'
      path: '/monitoramento'
      fullPath: '/admin/monitoramento'
      preLoaderRoute: typeof AdminMonitoramentoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/licencas': {
      id: '/admin/licencas'
      path: '/licencas'
      fullPath: '/admin/licencas'
      preLoaderRoute: typeof AdminLicencasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinaturas': {
      id: '/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas/$tenantId': {
      id: '/admin/empresas/$tenantId'
      path: '/$tenantId'
      fullPath: '/admin/empresas/$tenantId'
      preLoaderRoute: typeof AdminEmpresasTenantIdRouteImport
      parentRoute: typeof AdminEmpresasRoute
    }
  }
}

interface AdminEmpresasRouteChildren {
  AdminEmpresasTenantIdRoute: typeof AdminEmpresasTenantIdRoute
}

const AdminEmpresasRouteChildren: AdminEmpresasRouteChildren = {
  AdminEmpresasTenantIdRoute: AdminEmpresasTenantIdRoute,
}

const AdminEmpresasRouteWithChildren = AdminEmpresasRoute._addFileChildren(
  AdminEmpresasRouteChildren,
)

interface AdminRouteChildren {
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEmpresasRoute: typeof AdminEmpresasRouteWithChildren
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminLicencasRoute: typeof AdminLicencasRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMonitoramentoRoute: typeof AdminMonitoramentoRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEmpresasRoute: AdminEmpresasRouteWithChildren,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminLicencasRoute: AdminLicencasRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMonitoramentoRoute: AdminMonitoramentoRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AtendimentoRouteChildren {
  AtendimentoClientesRoute: typeof AtendimentoClientesRoute
  AtendimentoFavoritosRoute: typeof AtendimentoFavoritosRoute
  AtendimentoHistoricoRoute: typeof AtendimentoHistoricoRoute
  AtendimentoInboxRoute: typeof AtendimentoInboxRoute
  AtendimentoPerfilRoute: typeof AtendimentoPerfilRoute
  AtendimentoIndexRoute: typeof AtendimentoIndexRoute
}

const AtendimentoRouteChildren: AtendimentoRouteChildren = {
  AtendimentoClientesRoute: AtendimentoClientesRoute,
  AtendimentoFavoritosRoute: AtendimentoFavoritosRoute,
  AtendimentoHistoricoRoute: AtendimentoHistoricoRoute,
  AtendimentoInboxRoute: AtendimentoInboxRoute,
  AtendimentoPerfilRoute: AtendimentoPerfilRoute,
  AtendimentoIndexRoute: AtendimentoIndexRoute,
}

const AtendimentoRouteWithChildren = AtendimentoRoute._addFileChildren(
  AtendimentoRouteChildren,
)

interface ConfiguracoesRouteChildren {
  ConfiguracoesEmpresaRoute: typeof ConfiguracoesEmpresaRoute
  ConfiguracoesGeralRoute: typeof ConfiguracoesGeralRoute
  ConfiguracoesHorariosRoute: typeof ConfiguracoesHorariosRoute
  ConfiguracoesIntegracoesRoute: typeof ConfiguracoesIntegracoesRoute
  ConfiguracoesMensagensRoute: typeof ConfiguracoesMensagensRoute
  ConfiguracoesPermissoesRoute: typeof ConfiguracoesPermissoesRoute
  ConfiguracoesSegurancaRoute: typeof ConfiguracoesSegurancaRoute
  ConfiguracoesUsuariosRoute: typeof ConfiguracoesUsuariosRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesEmpresaRoute: ConfiguracoesEmpresaRoute,
  ConfiguracoesGeralRoute: ConfiguracoesGeralRoute,
  ConfiguracoesHorariosRoute: ConfiguracoesHorariosRoute,
  ConfiguracoesIntegracoesRoute: ConfiguracoesIntegracoesRoute,
  ConfiguracoesMensagensRoute: ConfiguracoesMensagensRoute,
  ConfiguracoesPermissoesRoute: ConfiguracoesPermissoesRoute,
  ConfiguracoesSegurancaRoute: ConfiguracoesSegurancaRoute,
  ConfiguracoesUsuariosRoute: ConfiguracoesUsuariosRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface InboxRouteChildren {
  InboxConversationIdRoute: typeof InboxConversationIdRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxConversationIdRoute: InboxConversationIdRoute,
  InboxIndexRoute: InboxIndexRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgenteIaRoute: AgenteIaRoute,
  AjudaRoute: AjudaRoute,
  AtendentesRoute: AtendentesRoute,
  AtendimentoRoute: AtendimentoRouteWithChildren,
  AutomacoesRoute: AutomacoesRoute,
  CampanhasRoute: CampanhasRoute,
  ChamadosRoute: ChamadosRoute,
  ChatbotRoute: ChatbotRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  ContatosRoute: ContatosRoute,
  DepartamentosRoute: DepartamentosRoute,
  EmpresasRoute: EmpresasRoute,
  EtiquetasRoute: EtiquetasRoute,
  FilasRoute: FilasRoute,
  HistoricoRoute: HistoricoRoute,
  InboxRoute: InboxRouteWithChildren,
  InstanciasRoute: InstanciasRoute,
  LoginRoute: LoginRoute,
  MensagensRapidasRoute: MensagensRapidasRoute,
  PerfilRoute: PerfilRoute,
  PerfisRoute: PerfisRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
