export const PERMISSIONS = [
  "users.read",
  "users.manage",
  "departments.read",
  "departments.manage",
  "roles.read",
  "roles.manage",
  "crm.read",
  "crm.manage",
  "conversations.read",
  "conversations.assign",
  "conversations.manage",
  "messages.send",
  "connections.read",
  "connections.manage",
  "chat.contacts.edit",
  "chat.customer_link.edit",
  "chat.tags.use",
  "chat.tags.manage",
  "chat.leads.read",
  "chat.contacts.read",
  "chat.phone.read",
  "chat.messages.delete",
  "chat.messages.edit",
  "chat.quick_replies.read",
  "chat.quick_replies.manage",
  "tickets.read",
  "tickets.create",
  "tickets.update",
  "tickets.assign",
  "tickets.status.update",
  "tickets.comment",
  "tickets.attachments.upload",
  "tickets.attachments.delete",
  "tickets.manage",
  "campaigns.read",
  "campaigns.create",
  "campaigns.update",
  "campaigns.schedule",
  "campaigns.start",
  "campaigns.pause",
  "campaigns.cancel",
  "campaigns.duplicate",
  "campaigns.recipients.read",
  "campaigns.manage",
  "chat.contacts.block",
  "chat.audio.send",
  "chat.agent_name.show",
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

export const TENANT_ADMIN_PERMISSIONS: PermissionKey[] = [...PERMISSIONS];

export const SUPERVISOR_PERMISSIONS: PermissionKey[] = [
  "users.read",
  "departments.read",
  "departments.manage",
  "roles.read",
  "crm.read",
  "crm.manage",
  "conversations.read",
  "conversations.assign",
  "conversations.manage",
  "messages.send",
  "connections.read",
  "connections.manage",
  "chat.contacts.edit",
  "chat.customer_link.edit",
  "chat.tags.use",
  "chat.tags.manage",
  "chat.leads.read",
  "chat.contacts.read",
  "chat.phone.read",
  "chat.quick_replies.read",
  "chat.quick_replies.manage",
  "tickets.read",
  "tickets.create",
  "tickets.update",
  "tickets.assign",
  "tickets.status.update",
  "tickets.comment",
  "tickets.attachments.upload",
  "tickets.attachments.delete",
  "tickets.manage",
  "campaigns.read",
  "campaigns.create",
  "campaigns.update",
  "campaigns.schedule",
  "campaigns.recipients.read",
  "campaigns.duplicate",
  "chat.audio.send",
  "chat.agent_name.show",
];

export const AGENT_PERMISSIONS: PermissionKey[] = [
  "departments.read",
  "crm.read",
  "conversations.read",
  "conversations.assign",
  "conversations.manage",
  "messages.send",
  "connections.read",
  "chat.contacts.read",
  "chat.tags.use",
  "chat.leads.read",
  "chat.quick_replies.read",
  "tickets.read",
  "tickets.create",
  "tickets.status.update",
  "tickets.comment",
  "tickets.attachments.upload",
  "campaigns.read",
  "chat.audio.send",
  "chat.agent_name.show",
];

export function isPermissionKey(value: string): value is PermissionKey {
  return (PERMISSIONS as readonly string[]).includes(value);
}
